# Generated by Django 4.2.7 on 2025-03-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(500, 'Starter'), (1500, 'Silver'), (5000, 'Gold'), (7500, 'Platinum'), (10000, 'Diamond'), (25000, 'VIP')], unique=True)),
                ('daily_return', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['timestamp'], name='investments_timesta_799253_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('initial_gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.investmentpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='investments_user_id_14912f_idx'), models.Index(fields=['end_date'], name='investments_end_dat_03b352_idx')],
            },
        ),
    ]
