# Generated by Django 4.2.7 on 2025-04-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='total_earned',
            new_name='total_earned_usxw',
        ),
    ]
