# Generated by Django 4.2.7 on 2025-04-02 03:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import encrypted_model_fields.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('client_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='client ID')),
                ('username', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='username')),
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20, verbose_name='verification status')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(blank=True, max_length=20, unique=True, validators=[user.models.validate_phone_number], verbose_name='mobile number')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('usd_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usxw_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stripe_customer_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, unique=True)),
                ('stripe_account_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, unique=True)),
                ('kyc_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20, verbose_name='KYC Status')),
                ('document_expiry', models.DateField(blank=True, null=True, verbose_name='Document Expiry')),
                ('jurisdiction', models.CharField(choices=[('US', 'United States'), ('EU', 'European Union'), ('SG', 'Singapore'), ('AE', 'United Arab Emirates')], default='US', max_length=50, verbose_name='Jurisdiction')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=10, verbose_name='Risk Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted Status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (max 2MB, 512x512px)', upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Avatar')),
                ('bio', models.CharField(blank=True, help_text='Short personal description (80 characters max)', max_length=80, verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(editable=False, max_length=10, verbose_name='OTP Code')),
                ('purpose', models.CharField(choices=[('VA', 'Verification'), ('PR', 'Password Reset'), ('2F', 'Two-Factor Auth')], default='VA', max_length=3, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='user_otp_user_id_550e3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('NATIONAL_ID', 'National ID')], max_length=20)),
                ('document_front', models.FileField(upload_to='kyc/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('document_back', models.FileField(blank=True, upload_to='kyc/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('selfie', models.FileField(blank=True, null=True, upload_to='kyc/selfies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('verification_result', models.JSONField(blank=True, null=True)),
                ('is_auto_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'indexes': [models.Index(fields=['user', 'document_type'], name='user_kycver_user_id_c72545_idx'), models.Index(fields=['next_review_date'], name='user_kycver_next_re_f0c032_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'client_id'], name='user_user_email_ad4631_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verification_status', 'is_active'], name='user_user_verific_0b544c_idx'),
        ),
    ]
