# Generated by Django 4.2.7 on 2025-03-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marketing_prefs',
        ),
    ]
