# Generated by Django 4.2.7 on 2025-04-08 04:50

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_account_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True),
        ),
    ]
