# Generated by Django 4.2.7 on 2025-03-19 07:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_city_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country'),
        ),
    ]
