# Generated by Django 4.2.7 on 2025-03-19 09:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[user.models.validate_phone_number], verbose_name='mobile number'),
        ),
    ]
