# Generated by Django 4.2.7 on 2025-03-20 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='is_auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to='kyc/selfies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verification_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_back',
            field=models.FileField(blank=True, upload_to='kyc/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_front',
            field=models.FileField(upload_to='kyc/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('NATIONAL_ID', 'National ID')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
