# Generated by Django 4.2.7 on 2025-04-01 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('usxw_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_count', models.PositiveIntegerField(default=0)),
                ('daily_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_p_user_id_7c9e42_idx'), models.Index(fields=['timestamp'], name='analytics_p_timesta_f7605d_idx')],
            },
        ),
    ]
