# Generated by Django 4.2.7 on 2025-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
